{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import sys\n",
    "import os\n",
    "from sklearn.cluster import DBSCAN\n",
    "\n",
    "# Get the clustering results\n",
    "def clustering(p_value):\n",
    "\n",
    "    # This parameter was tested using cluster_test script, may not be optimal\n",
    "    db = DBSCAN(eps=0.08, min_samples=500)\n",
    "    # get rid of na values for clustering purposes\n",
    "    p_value = np.asarray(p_value)\n",
    "    p_value = p_value[np.logical_not(np.logical_or(np.isnan(p_value), (p_value == 0)))]\n",
    "    p_value = np.log(p_value)\n",
    "\n",
    "    y_db = db.fit_predict(p_value.reshape(-1, 1))\n",
    "    n_clusters = len(set(db.labels_))\n",
    "    if n_clusters != 2:\n",
    "        return \"invalid\"\n",
    "    \n",
    "    threshold = np.max(p_value[y_db == -1])\n",
    "    return threshold\n",
    "\n",
    "# Find consecutive groups with same cluster label\n",
    "def consecutive(data):\n",
    "    # split the abnormal index into consecutive groups\n",
    "    return np.split(data, np.where(np.diff(data) != 1)[0] + 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "name_list = os.listdir(\"Aug 13/varied_fisher/1\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['fisher_3.tombo.per_read_stats.csv']"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "name_list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n",
      "/apps/python/3.6-conda5.2/lib/python3.6/site-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in less\n"
     ]
    }
   ],
   "source": [
    "for input_name in name_list:\n",
    "    if 'csv' not in input_name:\n",
    "        continue\n",
    "    # read and process the data\n",
    "    df = pd.read_csv('Aug 13/varied_fisher/1/' + input_name)\n",
    "    start_pos = 0\n",
    "    end_pos = df.shape[0]\n",
    "\n",
    "    # Create empty df for output\n",
    "    out = pd.DataFrame(columns=['RNA', 'peak', 'start', 'end', 'len', 'min p-val'])\n",
    "\n",
    "    \n",
    "    dummy_counter = 0\n",
    "    start_index = int(df.columns[2])\n",
    "    # peak_pick_up_counter = 0\n",
    "\n",
    "    for i in range(start_pos, end_pos):\n",
    "        p_val = df.loc[i]\n",
    "        p_val = list(p_val)\n",
    "        read_id = p_val[1]\n",
    "        # deal with the very 1st row of data\n",
    "        if np.isnan(read_id):\n",
    "            read_id = 0\n",
    "        p_val = p_val[2:]\n",
    "\n",
    "        baseline = clustering(p_val)\n",
    "        if baseline == \"invalid\":\n",
    "            continue\n",
    "\n",
    "        y = np.log(p_val)\n",
    "\n",
    "        # this threshold can be modified for certain dataset\n",
    "        # ind is the indexes of abnormal data\n",
    "        ind = np.where(y < baseline)[0]\n",
    "\n",
    "        cons = consecutive(ind)\n",
    "\n",
    "\n",
    "        possible_change = []\n",
    "\n",
    "\n",
    "        for group in cons:\n",
    "            size = len(group)\n",
    "\n",
    "            # for every 8 indexes,\n",
    "            # put them into a subgroup to eliminate the noises\n",
    "\n",
    "            first = 0\n",
    "\n",
    "            if size >= 2:\n",
    "                # print the 1st and last index of the abnormal group\n",
    "                if first == 0:\n",
    "                    possible_change.append((group[0], group[-1]))\n",
    "                    first = 1\n",
    "\n",
    "        if len(possible_change) > 0:\n",
    "            peak_pick_up_counter += 1\n",
    "\n",
    "        count = 1\n",
    "        for pair in possible_change:\n",
    "            curr_avg = np.min(list(p_val)[pair[0]:pair[1] + 1])\n",
    "            out.loc[dummy_counter] = [int(read_id), count, pair[0] + start_index, pair[1] + start_index, pair[1]-pair[0]+1, curr_avg]\n",
    "            dummy_counter += 1\n",
    "            count += 1\n",
    "\n",
    "    print(dummy_counter, peak_pick_up_counter)\n",
    "    \n",
    "    out.to_csv(\"Aug 13/result/\" + input_name + \"_min.csv\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.6 (Conda 5.2) [python/3.6-conda5.2]",
   "language": "python",
   "name": "sys_python36conda"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}